# Generated by Django 3.2.25 on 2026-05-21 16:41

from django.db import migrations, models
import utils.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20180501_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRun',
            fields=[
                ('id', models.TextField(db_index=True, default=utils.shortcuts.rand_str, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('username', models.TextField()),
                ('code', models.TextField()),
                ('language', models.TextField()),
                ('result', models.IntegerField(db_index=True, default=6)),
                ('info', models.JSONField(default=dict)),
                ('statistic_info', models.JSONField(default=dict)),
                ('ip', models.TextField(null=True)),
            ],
            options={
                'db_table': 'code_run',
                'ordering': ('-create_time',),
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='statistic_info',
            field=models.JSONField(default=dict),
        ),
    ]
