# Generated by Django 3.2.25 on 2026-08-05 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0015_auto_20260421_1435'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BossExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(null=True)),
                ('topic_area', models.JSONField(default=list)),
                ('boss_topic', models.TextField()),
                ('difficulty', models.TextField(default='Mid')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('time_limit', models.IntegerField(null=True)),
                ('passing_score', models.IntegerField(default=60)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boss_exam',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(null=True)),
                ('topic', models.TextField()),
                ('difficulty', models.TextField(default='Mid')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('time_limit', models.IntegerField(null=True)),
                ('meta', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_set',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('total_score', models.IntegerField(default=0)),
                ('status', models.TextField(default='in_progress')),
                ('exercise_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercise.exerciseset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_submission',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('question_type', models.TextField(default='choice')),
                ('content', utils.models.RichTextField()),
                ('choices', models.JSONField(default=list)),
                ('correct_answer', models.TextField(null=True)),
                ('score', models.IntegerField(default=10)),
                ('explanation', models.TextField(null=True)),
                ('exercise_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercise.exerciseset')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.problem')),
            ],
            options={
                'db_table': 'exercise_question',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BossSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('status', models.TextField(default='in_progress')),
                ('ai_evaluation', models.TextField(null=True)),
                ('passed', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercise.bossexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boss_submission',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='BossQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('question_type', models.TextField(default='choice')),
                ('content', utils.models.RichTextField()),
                ('choices', models.JSONField(default=list)),
                ('correct_answer', models.TextField(null=True)),
                ('score', models.IntegerField(default=10)),
                ('topic', models.TextField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercise.bossexam')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.problem')),
            ],
            options={
                'db_table': 'boss_question',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExerciseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('score', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField(null=True)),
                ('graded_at', models.DateTimeField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercisequestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exercise.exercisesubmission')),
            ],
            options={
                'db_table': 'exercise_answer',
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.CreateModel(
            name='BossAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('score', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.bossquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exercise.bosssubmission')),
            ],
            options={
                'db_table': 'boss_answer',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
