# Generated by Django 3.2.25 on 2026-08-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='max_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='show_ranking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='show_score',
            field=models.BooleanField(default=True),
        ),
    ]
